# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connection.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_pb2 as game__pb2
import match_pb2 as match__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x1a\ngame.proto\x1a\x0bmatch.proto\"\x86\x01\n\rClientMessage\x12\"\n\x0bgame_update\x18\x01 \x01(\x0b\x32\x0b.GameUpdateH\x00\x12$\n\x0c\x63reate_match\x18\x02 \x01(\x0b\x32\x0c.CreateMatchH\x00\x12 \n\njoin_match\x18\x03 \x01(\x0b\x32\n.JoinMatchH\x00\x42\t\n\x07message\"j\n\rServerMessage\x12\"\n\x0bgame_update\x18\x01 \x01(\x0b\x32\x0b.GameUpdateH\x00\x12\x17\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x12\x11\n\x07success\x18\x03 \x01(\x08H\x00\x42\t\n\x07message\"\x8f\x01\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.Error.Type\"Z\n\x04Type\x12\x0e\n\nERROR_NONE\x10\x00\x12\x19\n\x15\x45RROR_MATCH_NOT_FOUND\x10\x01\x12\x14\n\x10\x45RROR_MATCH_FULL\x10\x02\x12\x11\n\rERROR_UNKNOWN\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=46
  _globals['_CLIENTMESSAGE']._serialized_end=180
  _globals['_SERVERMESSAGE']._serialized_start=182
  _globals['_SERVERMESSAGE']._serialized_end=288
  _globals['_ERROR']._serialized_start=291
  _globals['_ERROR']._serialized_end=434
  _globals['_ERROR_TYPE']._serialized_start=344
  _globals['_ERROR_TYPE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
