name: Deploy Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date for tag
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t tankinho-server .
          docker tag tankinho-server zrafaf/tankinho:latest
          docker tag tankinho-server zrafaf/tankinho:${{ steps.date.outputs.date }}
          docker push zrafaf/tankinho:latest
          docker push zrafaf/tankinho:${{ steps.date.outputs.date }}